### ISSUE TITLE
Unable to resolve module 'some-dep'

### ISSUE THREAD

**Issue by avet-m** [Carimus/metro-symlinked-deps#2]
Hi!

I'm trying to create a symlink by following this steps

1. Installed **metro-symlinked-deps** package
2. Changed my **metro.config.js** settings to 

```
const {
  applyConfigForLinkedDependencies,
} = require('@carimus/metro-symlinked-deps');

module.exports = applyConfigForLinkedDependencies(
  {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
  },
);

```

3. cd ~/projects/some-dep
4. npm link  # Step 1. **(also tried with yarn )**
5. cd ~/projects/my-app
6. npm link some-dep  # Step 2. **(also tried with yarn )**
7. react-native start
8. react-native run-ios

And getting the error **"Unable to resolve module 'some-dep'"**

@bericp1 
Any ideas what's is going wrong ? Thx

**Comment by bericp1** [comment]
@avet-m -- which repo did you install `metro-symlinked-deps` in? The `some-dep` or the `my-app`? It should be installed in `my-app`.

I'd also recommend explicitly passing in `projectRoot` and possibly `blacklistLinkedModules` per the example in the README.

Additionally, when running the bundler with these modifications, it's typically best to always start it with `--reset-cache`.

```bash
react-native start --reset-cache
```

**Comment by avet-m** [comment]
@bericp1 I have tried to add this configs
```
{
    projectRoot: __dirname,
    blacklistLinkedModules: ['react-native'],
}
```
, and also tried --reset-cach

I installed **sode-dep** package in my-app

**Comment by bericp1** [comment]
@avet-m did you also install `metro-symlinked-deps` in your app (_not_ in the dep)? Do you have code you can share?

**Comment by avet-m** [comment]
@bericp1 yes, I installed `metro-symlinked-deps`, I use it in `metro.config.js`

**Comment by bericp1** [comment]
Can you share the full bundler output or the code in the repositories? You might try fully cleaning and up and reinstalling everything as well and then re-linking. The bundler is super finicy.

**Comment by avet-m** [comment]
Unfortunately, just now I can't share full bundler output, because  I have created monorepo project for linking my packages. 

Anyway, I tried reinstall everything and re-linking, but no-result, will try again

Thank you for response

**Comment by noambonnie** [comment]
I'm experiencing the same issue. I believe I did everything according to the instructions.

Bundler log:
```
 BUNDLE  [android, dev] ./index.js ▓▓░░░░░░░░░░░░░░ 16.0% (9/139)::ffff:127.0.0.1 - - [10/Mar/2020:16:10:30 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
error: bundling failed: Error: Unable to resolve module `company-rn` from `CompanyExample.js`: company-rn could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/myuser/dev/sdks/react-native/RNCompanyExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

In the App root:
`$ ls -l node_modules/company-rn`
`lrwxr-xr-x  1 myuser  staff  58 Mar 10 12:06 node_modules/company-rn -> ../../../../../../../usr/local/lib/node_modules/company-rn`

so the link is there.

And just to make sure it points to the right folder:
`$ ls -l ../../../../../../../usr/local/lib/node_modules/company-rn`
`lrwxr-xr-x  1 root  wheel  40 Mar 10 12:00 ../../../../../../../usr/local/lib/node_modules/company-rn -> /Users/myuser/dev/sdks/react-native/sdk`

which in turn points to:
`$ ls -l /Users/myuser/dev/sdks/react-native/sdk`
```
-rw-r--r--  1 myuser   staff  579 Mar  5 16:50 README.md
-rw-r--r--  1 myuser   staff   72 Mar  6 17:48 index.js
-rw-r--r--  1 root     staff   73 Mar  5 17:51 package-lock.json
-rw-r--r--  1 myuser   staff  348 Mar  6 17:48 package.json
drwxr-xr-x  7 myuser   staff  224 Mar 10 09:32 src
```

metro.config.js:
```
const {
  applyConfigForLinkedDependencies,
} = require('@carimus/metro-symlinked-deps');

module.exports = applyConfigForLinkedDependencies(
  {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
    },
  },
  {
    projectRoot: '/Users/myuser/dev/sdks/react-native/RNCompanyExample',
    blacklistLinkedModules: ['react-native'],
  },
);
```

**Comment by joker-777** [comment]
Guys, I have the same issue. Could you make it work somehow?

**Comment by ErikBjare** [comment]
I've also stumbled into the same issue. Using Expo to build (with `expo start --clear`).

My config:

```
const { applyConfigForLinkedDependencies } = require('@carimus/metro-symlinked-deps');

module.exports = applyConfigForLinkedDependencies(
  {},
  {
    projectRoot: __dirname,
    blacklistLinkedModules: ['react-native', 'axios'],  // axios is probably not needed here.
  }
);
```

I do get the message stating:

```
Warning: you have symlinked dependencies in node_modules!

The following directories are symlink destinations of one or more node_modules
(i.e. `yarn link` or `npm link` was used to link in a dependency locally). Metro
bundler doesn't support symlinks so instead we'll manually watch the symlink
destination. Note that if you get errors about name collisions, you need to inform
`@carimus/metro-symlinked-deps` of the colliding module(s) in metro.config.js via the
`blacklistLinkedModules` option passed to `applyConfigForLinkedDependencies`.
-   [my project root]/client
Colliding modules that are blacklisted if they show up in the symlinked dependencies:
-   react-native
-   axios
```

**Comment by davidfarinha** [comment]
Also getting the same error in a brand new react-native project with this package installed.

```
error: Error: Unable to resolve module `my-symlinked-package` from `App.tsx`: my-symlinked-package could not be found within the project.
```

My metro.config.js:
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const {
  applyConfigForLinkedDependencies,
} = require('@carimus/metro-symlinked-deps');

module.exports = applyConfigForLinkedDependencies(
  {
      transformer: {
          getTransformOptions: async () => ({
              transform: {
                  experimentalImportSupport: false,
                  inlineRequires: false,
              },
          }),
      },
  },
  {
      projectRoot: __dirname,
      blacklistLinkedModules: ['react-native'],
  },
);

```

My package.json:
```
{
  "name": "haul",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "my-symlinked-package": "../my-symlinked-package",
    "react": "16.11.0",
    "react-native": "0.62.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@carimus/metro-symlinked-deps": "^1.1.0",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

**Comment by luogao** [comment]
same issue

**Comment by luogao** [comment]
After some dig out, I found it need add the linking package's name in `package.json`
I try like this:
```json
"dependencies": {
    "myPackageName" : "*"
},
```
is this necessary? or  am I doing wrong? 🥺🥺🥺

please help~
